package janelas;

import data.access.object.DAOControlador;
import data.access.object.DAOPonto;
import data.access.object.DAOUsuario;
import diario.de.bordo.Versao;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lembrete.ponto.Ponto;
import model.Controlador;
import model.PontoPerfil;
import seguranca.Cypher;

/**
 *
 * @author joao.oliveira
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        senhaTxt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        ufCmb = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        setoresTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        statusLembreteButton = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hora1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        minuto1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        perfilCmb = new javax.swing.JComboBox();
        hora2 = new javax.swing.JComboBox();
        hora3 = new javax.swing.JComboBox();
        hora4 = new javax.swing.JComboBox();
        hora5 = new javax.swing.JComboBox();
        hora6 = new javax.swing.JComboBox();
        hora7 = new javax.swing.JComboBox();
        hora8 = new javax.swing.JComboBox();
        minuto2 = new javax.swing.JComboBox();
        minuto3 = new javax.swing.JComboBox();
        minuto4 = new javax.swing.JComboBox();
        minuto5 = new javax.swing.JComboBox();
        minuto6 = new javax.swing.JComboBox();
        minuto7 = new javax.swing.JComboBox();
        minuto8 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diário de Bordo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        jLabel4.setText("UF:");

        ufCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CE", "MA", "PI" }));
        ufCmb.setSelectedIndex(-1);
        ufCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ufCmbItemStateChanged(evt);
            }
        });

        jLabel3.setText("Setor");

        setoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(setoresTable);

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(senhaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuarioTxt)
                                    .addComponent(ufCmb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ufCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", jPanel1);

        jLabel5.setText("Status:");

        statusLembreteButton.setText("Desativado");
        statusLembreteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusLembreteButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Horários (24hrs)");

        jLabel7.setText("1º:");
        jLabel7.setToolTipText("");

        hora1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText(":");

        minuto1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("2º:");
        jLabel9.setToolTipText("");

        jLabel10.setText(":");

        jLabel11.setText("3º:");
        jLabel11.setToolTipText("");

        jLabel12.setText(":");

        jLabel13.setText("4º:");
        jLabel13.setToolTipText("");

        jLabel14.setText(":");

        jLabel15.setText("5º:");
        jLabel15.setToolTipText("");

        jLabel16.setText(":");

        jLabel17.setText("6º:");
        jLabel17.setToolTipText("");

        jLabel18.setText(":");

        jLabel19.setText("7º:");
        jLabel19.setToolTipText("");

        jLabel20.setText(":");

        jLabel21.setText("8º:");
        jLabel21.setToolTipText("");

        jLabel22.setText(":");

        jButton3.setText("Salvar Perfil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel23.setText("Perfil:");

        perfilCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        perfilCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                perfilCmbItemStateChanged(evt);
            }
        });

        hora2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hora3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hora4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hora5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hora6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hora7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hora8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minuto2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minuto3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minuto4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minuto5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minuto6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minuto7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minuto8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minuto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hora5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minuto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hora6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minuto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hora7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minuto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hora8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minuto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(minuto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(minuto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(minuto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusLembreteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(perfilCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(statusLembreteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(perfilCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(minuto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(hora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(hora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(hora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(hora5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(hora6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(hora7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(hora8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lembrete de Ponto", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean iniciado;

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.usuarioTxt.setText(System.getProperty("user.name"));
        Versao vInfo = new Versao();
        this.setTitle("Diário de Bordo - Build: " + vInfo.getVersion());
        Ponto.setAtivado(false);
//        try {
//           // System.out.println(Cypher.encrypt("senha@321"));
//            senhas();
//        } catch (Exception ex) {
//            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
//        }

        String pastaRaiz = System.getProperty("user.dir");

        if (pastaRaiz.contains("CONTROLE LOCAL DIR_CE")) {

            JOptionPane.showMessageDialog(this, "Não é permitido executar o programa nesse caminho! \r\n COPIE o arquivo para sua área de trabalho e execute!");
            this.dispose();

        } else {

            carregaPerfis();

            this.hora1.removeAllItems();
            this.hora2.removeAllItems();
            this.hora3.removeAllItems();
            this.hora4.removeAllItems();
            this.hora5.removeAllItems();
            this.hora6.removeAllItems();
            this.hora7.removeAllItems();
            this.hora8.removeAllItems();

            this.minuto1.removeAllItems();
            this.minuto2.removeAllItems();
            this.minuto3.removeAllItems();
            this.minuto4.removeAllItems();
            this.minuto5.removeAllItems();
            this.minuto6.removeAllItems();
            this.minuto7.removeAllItems();
            this.minuto8.removeAllItems();

            for (int i = 0; i <= 23; i++) {

                String min = String.format("%02d", i);
                this.hora1.addItem(min);
                this.hora2.addItem(min);
                this.hora3.addItem(min);
                this.hora4.addItem(min);
                this.hora5.addItem(min);
                this.hora6.addItem(min);
                this.hora7.addItem(min);
                this.hora8.addItem(min);

            }

            for (int i = 0; i <= 59; i++) {

                String seg = String.format("%02d", i);
                this.minuto1.addItem(seg);
                this.minuto2.addItem(seg);
                this.minuto3.addItem(seg);
                this.minuto4.addItem(seg);
                this.minuto5.addItem(seg);
                this.minuto6.addItem(seg);
                this.minuto7.addItem(seg);
                this.minuto8.addItem(seg);

            }

        }

        iniciado = true;

    }//GEN-LAST:event_formWindowOpened

    private void ufCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ufCmbItemStateChanged

        Object item = evt.getItem();
        String uf = item.toString();

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            String[] colunas = {"Setor", " "};
            DefaultTableModel dadosSetores = new DefaultTableModel(new Object[0][0], colunas) {

                @Override
                public boolean isCellEditable(int row, int col) {
                    return (col == 1);
                }

                @Override
                public Class getColumnClass(int column) {
                    return (getValueAt(0, column).getClass());
                }

            };

            data.access.object.DAOSetor DAOSetores = new data.access.object.DAOSetor();
            List setores = null;

            try {

                setores = DAOSetores.getSetoresPorUF(uf);

            } catch (SQLException | ClassNotFoundException ex) {

                JOptionPane.showMessageDialog(null, ex);

            }

            for (int i = 0; i < setores.size(); i++) {

                Map obj = (Map) setores.get(i);
                Object[] linha = {obj.get("SETOR"), Boolean.FALSE};
                dadosSetores.addRow(linha);

            }

            this.setoresTable.setModel(dadosSetores);
            this.setoresTable.getColumnModel().getColumn(0).setMinWidth(150);
            this.setoresTable.getColumnModel().getColumn(0).setMaxWidth(300);

        }

    }//GEN-LAST:event_ufCmbItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        janelas.FormCadastro frm = new janelas.FormCadastro();
        frm.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String user = this.usuarioTxt.getText();
        String pass = this.senhaTxt.getText();
        DAOUsuario UsuarioDAO = new DAOUsuario();
        String cargo = "";
        String uf = "";

        try {
            cargo = UsuarioDAO.getCargo(user);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

        if (user.equals("")) {

            JOptionPane.showMessageDialog(null, "O USUARIO é obrigatório");
            return;

        } else if (pass.equals("")) {

            JOptionPane.showMessageDialog(null, "A SENHA é obrigatória");
            return;

        }

        if (this.ufCmb.getSelectedItem() == null & cargo.equals("CONTROLADOR")) {

            JOptionPane.showMessageDialog(null, "A UF é obrigatória");
            return;

        } else if (cargo.equals("CONTROLADOR")) {

            uf = this.ufCmb.getSelectedItem().toString();

        }

        ArrayList setores = new ArrayList();

        if (this.setoresTable.getRowCount() == 0 & cargo.equals("CONTROLADOR")) {

            JOptionPane.showMessageDialog(null, "Selecione uma UF!");
            return;

        }

        for (int i = 0; i <= this.setoresTable.getRowCount() - 1; i++) {

            if (this.setoresTable.getModel().getValueAt(i, 1) == Boolean.TRUE) {

                setores.add(this.setoresTable.getModel().getValueAt(i, 0));

            }

        }

        if (setores.isEmpty() & cargo.equals("CONTROLADOR")) {

            JOptionPane.showMessageDialog(null, "Selecione um ou mais setor(es)!");
            return;

        }

        seguranca.Autenticacao Autenticacao = new seguranca.Autenticacao();

        try {

            if (Autenticacao.autorizado(user, pass)) {

                switch (cargo) {
                    case "CONTROLADOR": {
                        if (Ponto.isAtivado()) {

                            String h1 = this.hora1.getSelectedItem().toString() + ":" + this.minuto1.getSelectedItem().toString();
                            String h2 = this.hora2.getSelectedItem().toString() + ":" + this.minuto2.getSelectedItem().toString();
                            String h3 = this.hora3.getSelectedItem().toString() + ":" + this.minuto3.getSelectedItem().toString();
                            String h4 = this.hora4.getSelectedItem().toString() + ":" + this.minuto4.getSelectedItem().toString();
                            String h5 = this.hora5.getSelectedItem().toString() + ":" + this.minuto5.getSelectedItem().toString();
                            String h6 = this.hora6.getSelectedItem().toString() + ":" + this.minuto6.getSelectedItem().toString();
                            String h7 = this.hora7.getSelectedItem().toString() + ":" + this.minuto7.getSelectedItem().toString();
                            String h8 = this.hora8.getSelectedItem().toString() + ":" + this.minuto8.getSelectedItem().toString();

                            Ponto.setHorarios(new String[]{h1, h2, h3, h4, h5, h6, h7, h8});

                        }
                        janelas.FormDiarioCon frm = new janelas.FormDiarioCon();
                        frm.setUsuario(user);
                        frm.setUf(uf);
                        frm.setSetores(setores);
                        frm.setVisible(true);
                        break;
                    }
                    case "SUPERVISOR": {
                        janelas.FormDiarioSup frm = new janelas.FormDiarioSup();
                        frm.setUsuario(user);
                        frm.setVisible(true);
                        break;
                    }
                    case "COORDENADOR": {
                        janelas.FormDiarioCoo frm = new janelas.FormDiarioCoo();
                        frm.setUsuario(user);
                        frm.setVisible(true);
                        break;
                    }
                }

                this.dispose();

            } else {

                JOptionPane.showMessageDialog(null, "Usuário Desconhecido!");

            }

        } catch (ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "Erro: " + ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Erro: " + ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void statusLembreteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusLembreteButtonActionPerformed

        if (this.statusLembreteButton.isSelected()) {

            this.statusLembreteButton.setText("Ativado");
            Ponto.setAtivado(true);

        } else {

            this.statusLembreteButton.setText("Desativado");
            Ponto.setAtivado(false);

        }

    }//GEN-LAST:event_statusLembreteButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String nmPerfil = JOptionPane.showInputDialog("Digite o nome do Perfil:");

        if (nmPerfil != null) {

            if (nmPerfil.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Nome de Perfil inválido!","Ops!",JOptionPane.ERROR_MESSAGE);
                return;
            }

            String h1 = this.hora1.getSelectedItem().toString() + ":" + this.minuto1.getSelectedItem().toString();
            String h2 = this.hora2.getSelectedItem().toString() + ":" + this.minuto2.getSelectedItem().toString();
            String h3 = this.hora3.getSelectedItem().toString() + ":" + this.minuto3.getSelectedItem().toString();
            String h4 = this.hora4.getSelectedItem().toString() + ":" + this.minuto4.getSelectedItem().toString();
            String h5 = this.hora5.getSelectedItem().toString() + ":" + this.minuto5.getSelectedItem().toString();
            String h6 = this.hora6.getSelectedItem().toString() + ":" + this.minuto6.getSelectedItem().toString();
            String h7 = this.hora7.getSelectedItem().toString() + ":" + this.minuto7.getSelectedItem().toString();
            String h8 = this.hora8.getSelectedItem().toString() + ":" + this.minuto8.getSelectedItem().toString();
            
            String horarioInvalido = "00:0000:0000:0000:0000:0000:0000:0000:00";
            String horarioConcatenado = h1 + h2 + h3 + h4 + h5 + h6 + h7 + h8;
            
            if(horarioConcatenado.equals(horarioInvalido)){
                JOptionPane.showMessageDialog(null, "Os horários não podem ser todos zerados!","Ops!",JOptionPane.ERROR_MESSAGE);
                return;               
            }

            PontoPerfil novoPerfil = new PontoPerfil();
            novoPerfil.setNome(nmPerfil);
            novoPerfil.setHorario1(h1);
            novoPerfil.setHorario2(h2);
            novoPerfil.setHorario3(h3);
            novoPerfil.setHorario4(h4);
            novoPerfil.setHorario5(h5);
            novoPerfil.setHorario6(h6);
            novoPerfil.setHorario7(h7);
            novoPerfil.setHorario8(h8);

            try {

                if (new DAOPonto().inserirPerfil(novoPerfil)) {

                    carregaPerfis();
                    JOptionPane.showMessageDialog(null, "Perfil Salvo!");

                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void perfilCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_perfilCmbItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED & iniciado) {

            String nmPerfil = evt.getItem().toString();

            if (!nmPerfil.isEmpty()) {

                ArrayList<PontoPerfil> horarios = new DAOPonto().getHorariosPorPerfil(nmPerfil);
                String[] h1 = horarios.get(0).getHorario1().split(":");
                String[] h2 = horarios.get(0).getHorario2().split(":");
                String[] h3 = horarios.get(0).getHorario3().split(":");
                String[] h4 = horarios.get(0).getHorario4().split(":");
                String[] h5 = horarios.get(0).getHorario5().split(":");
                String[] h6 = horarios.get(0).getHorario6().split(":");
                String[] h7 = horarios.get(0).getHorario7().split(":");
                String[] h8 = horarios.get(0).getHorario8().split(":");

                this.hora1.setSelectedIndex(Integer.parseInt(h1[0]));
                this.hora2.setSelectedIndex(Integer.parseInt(h2[0]));
                this.hora3.setSelectedIndex(Integer.parseInt(h3[0]));
                this.hora4.setSelectedIndex(Integer.parseInt(h4[0]));
                this.hora5.setSelectedIndex(Integer.parseInt(h5[0]));
                this.hora6.setSelectedIndex(Integer.parseInt(h6[0]));
                this.hora7.setSelectedIndex(Integer.parseInt(h7[0]));
                this.hora8.setSelectedIndex(Integer.parseInt(h8[0]));

                this.minuto1.setSelectedIndex(Integer.parseInt(h1[1]));
                this.minuto2.setSelectedIndex(Integer.parseInt(h2[1]));
                this.minuto3.setSelectedIndex(Integer.parseInt(h3[1]));
                this.minuto4.setSelectedIndex(Integer.parseInt(h4[1]));
                this.minuto5.setSelectedIndex(Integer.parseInt(h5[1]));
                this.minuto6.setSelectedIndex(Integer.parseInt(h6[1]));
                this.minuto7.setSelectedIndex(Integer.parseInt(h7[1]));
                this.minuto8.setSelectedIndex(Integer.parseInt(h8[1]));

            }

        }

    }//GEN-LAST:event_perfilCmbItemStateChanged

    void senhas() throws Exception {

        DAOControlador c = new DAOControlador();
        ArrayList<Controlador> d = c.getListaControladoresCompleta();

        for (Controlador con : d) {

            System.out.println(con.getNome() + ";" + con.getMatricula() + ";" + Cypher.decrypt(con.getSenha()));

        }

        //   System.out.println(Cypher.encrypt("senha@321"));
    }

    private void carregaPerfis() {

        this.perfilCmb.removeAllItems();
        ArrayList<PontoPerfil> perfis = new DAOPonto().getNomesPerfis();

        for (PontoPerfil p : perfis) {

            this.perfilCmb.addItem(p.getNome());

        }

        this.perfilCmb.setSelectedIndex(-1);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox hora1;
    private javax.swing.JComboBox hora2;
    private javax.swing.JComboBox hora3;
    private javax.swing.JComboBox hora4;
    private javax.swing.JComboBox hora5;
    private javax.swing.JComboBox hora6;
    private javax.swing.JComboBox hora7;
    private javax.swing.JComboBox hora8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox minuto1;
    private javax.swing.JComboBox minuto2;
    private javax.swing.JComboBox minuto3;
    private javax.swing.JComboBox minuto4;
    private javax.swing.JComboBox minuto5;
    private javax.swing.JComboBox minuto6;
    private javax.swing.JComboBox minuto7;
    private javax.swing.JComboBox minuto8;
    private javax.swing.JComboBox perfilCmb;
    private javax.swing.JPasswordField senhaTxt;
    private javax.swing.JTable setoresTable;
    private javax.swing.JToggleButton statusLembreteButton;
    private javax.swing.JComboBox ufCmb;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
